### ISSUE TITLE
error server

### ISSUE THREAD

**Issue by croziors** [McJty/ModTutorials#38]
16:29:19] [Netty Epoll Server IO #5/INFO] [FML]: Client protocol version 2
[16:29:19] [Netty Epoll Server IO #5/INFO] [FML]: Client attempting to join with 98 mods : buildcraftlib@7.99.17,p455w0rdslib@2.0.29,binniecore@2.5.0.165,universalmodifiers@1.12.2-1.0.9a,rftools@7.33                                      ,cofhcore@4.4.1,draconicevolution@2.3.11,reborncore@3.8.2.277,hammercore@1.9.9.6,jeibees@0.9.0.5,ae2stuff@0.7.0.4,mputils@1.5.4,bookshelf@2.3.544,forgelin@1.6.0,wizardry@0.8.5,wct@3.9.64,cofhworld@1.                                      1.1,darkutils@1.8.207,moreplanetsextras@1.12.2-1.0,morpheus@1.12-3.3.2,ftblib@5.0.2.14,props@2.6.0,galacticraftplanets@4.0.1.176,redstonearsenal@2.4.2,librarianliblate@9.4,guideapi@1.12-2.1.5-60,thau                                      mcraft@6.1.BETA13,mcjtylib_ng@2.6.7,malisisdoors@1.12.2-7.3.0,extratrees@2.5.0.165,malisiscore@1.12.2-6.4.0,ptrmodellib@1.0.2,botany@2.5.0.165,redstoneflux@2.0.1,valkyrielib@1.12.2-2.0.10b,botania@r1                                      .10-354,teslacorelib_registries@1.0.14,ic2@2.8.76-ex112,teslacorelib@1.0.14,elevatorid@1.3.6,FML@8.0.99.99,thermalexpansion@5.4.2,enderutilities@0.7.8,computercraft@1.80pr1,environmentaltech@1.12.2-2                                      .0.10a,bigreactors@1.12.2-0.4.5.48,codechickenlib@3.1.8.341,buildcraftcore@7.99.17,binniedesign@2.5.0.165,extracells@2.5.13,tesla@1.0.63,cucumber@1.1.0,asielib@1.0.0,librarianlib@9.4,jei@4.9.1.179,th                                      ermalcultivation@0.2.0,mekanism@1.12.2-9.4.10.345,thermalfoundation@2.4.1,bdlib@1.14.3.12,wawla@2.5.253,mcp@9.42,journeymap@1.12.2-5.5.2,appliedenergistics2@rv5-stable-11,compactmachines3@3.0.11,cham                                      eleon@1.12-4.1.3,inventorytweaks@1.63+release.109.220f184,extrabees@2.5.0.165,computronics@1.6.5,micdoodlecore@,enderstorage@2.4.2.126,rftoolspower@1.0.0,forge@14.23.3.2702,bloodmagic@1.12.2-2.2.12-9                                      7,brandonscore@2.4.2,ftbutilities@5.0.2.14,magicbees@1.0,ironchest@1.12.2-7.0.40.824,mysticalagriculture@1.6.10,zerocore@1.12-0.1.2.1,minecraft@1.12.2,tconstruct@1.12.2-2.10.0.81,solarfluxreborn@3.50                                      r,thermaldynamics@2.4.1,baubles@1.5.2,chickenchunks@2.4.1.71,stevescarts@2.4.18.92,genetics@2.5.0.165,mpbasic@1.4.5,extrautils2@1.0,bloodmoon@1.5.3,mantle@1.12-1.3.2.24,gravestone@1.10.1,storagedrawe                                      rs@1.12-5.3.5,galacticraftcore@4.0.1.176,mrtjpcore@2.1.1.27,aquaculture@1.6.2,forestry@5.8.0.291,moreplanets@2.0.14
[16:29:19] [Netty Epoll Server IO #5/INFO] [journeymap]: CLIENT
[16:29:23] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[16:29:23] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: croziors[/80.236.87.133:64819] logged in with entity id 193 at (-363.9013485586562, 65.49520087700593, -22.72258505308937                                      5)
[16:29:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: §ecroziors§r§e joined the game§r
[16:29:23] [Server thread/INFO] [journeymap]: croziors joining dimension 0
[16:29:23] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
        at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
        at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_902_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1205) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
        at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:376) [pl.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:165) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:72) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[MessageToMessageEncoder.class:?]
        ... 28 more
[16:29:23] [Server thread/INFO] [wizardry]: Sending module list to croziors
[16:29:23] [Server thread/INFO] [Mekanism]: Sent config to 'croziors.'
[16:29:23] [Server thread/INFO] [journeymap]: Sending log in packet.
[16:29:52] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at mcjty.lib.varia.Logging.warn(Logging.java:73) ~[Logging.class:?]
        at mcjty.rftools.blocks.logic.generic.LogicTileEntity.getFacing(LogicTileEntity.java:29) ~[LogicTileEntity.class:?]
        at mcjty.rftools.blocks.logic.generic.LogicSlabBlock.func_176221_a(LogicSlabBlock.java:294) ~[LogicSlabBlock.class:?]
        at mcjty.rftools.blocks.storage.LevelEmitterBlock.func_176221_a(LevelEmitterBlock.java:127) ~[LevelEmitterBlock.class:?]
        at forestry.apiculture.flowers.FlowerRegistry$AcceptedFlowerPredicate.test(FlowerRegistry.java:314) ~[FlowerRegistry$AcceptedFlowerPredicate.class:?]
        at forestry.apiculture.HasFlowersCache.update(HasFlowersCache.java:105) ~[HasFlowersCache.class:?]
        at forestry.apiculture.WorldgenBeekeepingLogic.canWork(WorldgenBeekeepingLogic.java:100) ~[WorldgenBeekeepingLogic.class:?]
        at forestry.apiculture.tiles.TileHive.func_73660_a(TileHive.java:124) ~[TileHive.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[16:29:52] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/minecraft/./crash-reports/crash-2018-05-21_16.29.52-server.txt
[16:29:52] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[16:29:52] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[16:29:52] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[16:29:52] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
[16:29:52] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/Nibiru
[16:29:52] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/ExtraUtils2_Quarry_Dim
[16:29:53] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/Storage Cell
[16:29:53] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/Diona
[16:29:53] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 0
[16:29:53] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -2544
[16:29:53] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -9999
[16:29:53] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 2
[16:29:53] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -2542
[16:29:54] [Server thread/INFO] [FML]: Unloading dimension 0
[16:29:54] [Server thread/INFO] [FML]: Unloading dimension -2544
[16:29:54] [Server thread/INFO] [FML]: Unloading dimension -9999
[16:29:54] [Server thread/INFO] [FML]: Unloading dimension 2
[16:29:54] [Server thread/INFO] [FML]: Unloading dimension -2542
[16:29:54] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -30
[16:29:54] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -2543
[16:29:54] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -2542
[16:29:54] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -29
[16:29:54] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -2544
[16:29:54] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -31
[16:29:54] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
[16:29:54] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[16:29:54] [Thread-27/INFO] [THAUMCRAFT]: Stopping aura thread for dim 0
[16:29:54] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[16:29:54] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[16:29:54] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players

**Comment by McJty** [comment]
Context please? What are you doing?

**Comment by croziors** [comment]
hello when i go on serveur i have this cash

**Comment by McJty** [comment]
With what exactly? What are you doing. Describe in DETAIL!
